_target_: src.dataloader_hydra.MaadaaMattingLoaderV2
image_path: ${..IMAGE_PATH}
foreground_path: ${..FOREGROUND_PATH}
background_path: ${..BACKGROUND_PATH}
image_size: ${..IMAGE_SIZE}
batch_size: ${..BATCH_SIZE}
mode: ${MODE}