defaults:
  - losses@loss: modnet

training:
  total_step: 150000
  device: cuda
  parallel: true
  optimizer:
    _target_: torch.optim.Adam
#    _target_: torch.optim.SGD
#    lr: 0.01
#    momentum: 0.9