shared_pre:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.SmallestMaxSize
      max_size: ${.....image_size}
    - _target_: albumentations.RandomCrop
      height: ${.....image_size}
      width: ${.....image_size}
composition: null
foreground:
background:
matte: null
shared_post:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.pytorch.ToTensorV2