defaults:
  - transforms@transforms: base_train_transforms


foreground_csv: "../data/AISegment/train_images.csv"
matte_csv: "../data/AISegment/train_mattes.csv"
background_dir: "../data/backgrounds/"
image_size: 512
mode: "train"

_target_: src.dataloader.AISegmentDistributedLoader
foreground_csv: ${..foreground_csv}
matte_csv: ${..matte_csv}
background_dir: ${..background_dir}
image_size: ${..image_size}
batch_size: 8
drop_last: false
shuffle: true
num_workers: 8
bg_per_fg: 1
mode: ${..mode}
use_one_img_per_dir: false