defaults:
  - transforms@image_transforms: base_transforms


_target_: src.dataloader.AISegmentInferenceLoader
image_dir: "../data/to_inference_10072021"
batch_size: 4
drop_last: false
shuffle: false
num_workers: 8
