defaults:
  - transforms@transforms: base_val_transforms


foreground_csv: "../data/AISegment/val_images.csv"
matte_csv: "../data/AISegment/val_mattes.csv"
background_dir: "../data/backgrounds/"
image_size: 512
mode: "test"

dataloader:
  _target_: src.dataloader.AISegmentDistributedLoader
  foreground_csv: ${..foreground_csv}
  matte_csv: ${..matte_csv}
  background_dir: ${..background_dir}
  image_size: ${..image_size}
  batch_size: 8
  drop_last: false
  shuffle: false
  num_workers: 8
  mode: ${..mode}
  bg_per_fg: 1
  use_one_img_per_dir: false
  shared_pre_transform: ${..transforms.shared_pre}
  composition_transform: ${..transforms.composition}
  foreground_transform: ${..transforms.foreground}
  background_transform: ${..transforms.background}
  matte_transform: ${..transforms.matte}
  shared_post_transform: ${..transforms.shared_post}