_target_: src.losses.ModNetLoss
_recursive_: true
blurer:
  _target_: src.model.GaussianBlurLayer
  n_channels: 3
  kernel_size: 3
semantic_scale: 10.0
detail_scale: 10.0
matte_scale: 1.0
average: true
detailed: false
device: ${..device}