defaults:
  - image_processing_modules@blurer: gaussian_blurer

_target_: src.losses.ModNetLoss
_recursive_: false
semantic_scale: 10.0
detail_scale: 10.0
matte_scale: 1.0
average: true
device: ${..device}