defaults:
  - logging@logging: wandb
  - inference: aisegment
  - training@training: maadaa
  - models@network: modnet_pvt
  - data@data: maadaa
  #- dataloaders@inference.dataloader: aisegment_inference
  - dataloaders@data.train.dataloader: maadaa_train
  - dataloaders@data.validation.dataloader: maadaa_train
  - transforms@data.train.transforms: base_train_transforms
  - transforms@data.validation.transforms: base_val_transforms

hydra:
  run:
    dir: .
  hydra_logging: null
  #output_subdir: null
  job_logging: null


testing:
  device: cuda

