# @package _global_
config:
  CHECKPOINT:
    DIR: "checkpoints"
    CHECKPOINT_FREQUENCY: 1
  DATA:
    NUM_DATALOADER_WORKERS: 8
    TRAIN:
      NAME: "maadaa"
      IMAGE_PATH: "../data/dataset_split/train/"
      FOREGROUND_PATH: "../data/foregrounds_split/train/"
      BACKGROUND_PATH: "../data/backgrounds/"
      BATCH_SIZE: 2
      SHUFFLE: True
      IMAGE_SIZE: 256
      TRANSFORMS:
        shared_pre:
          - name: A.SmallestMaxSize
            max_size: ${DATASET.TRAIN.IMAGE_SIZE}
          - name: A.RandomCrop
            height: ${DATASET.TRAIN.IMAGE_SIZE}
            width: ${DATASET.TRAIN.IMAGE_SIZE}
        composition:
          - name: A.Normalize
            mean: (0.5, 0.5, 0.5)
            std: (0.5, 0.5, 0.5)
        shared_post:
          A.ToTensorV2
      DROP_LAST: False
    TEST:
      NAME: "maadaa"
      IMAGE_PATH: "../data/one_image_dataset_split/val/"
      BATCH_SIZE: 2
      SHUFFLE: True
      IMAGE_SIZE: 256
      TRANSFORMS:
        shared_pre:
          - name: A.SmallestMaxSize
            max_size: ${DATASET.TRAIN.IMAGE_SIZE}
          - name: A.RandomCrop
            height: ${DATASET.TRAIN.IMAGE_SIZE}
            width: ${DATASET.TRAIN.IMAGE_SIZE}
        composition:
          - name: A.Normalize
            mean: (0.5, 0.5, 0.5)
            std: (0.5, 0.5, 0.5)
        shared_post:
          A.ToTensorV2
      DROP_LAST: False
  MODEL:
    NAME: modnet
    BACKBONE:
      NAME: resnet18
      PRETRAINED: True
    IN_CHANNELS: 3
    HR_CHANNELS: 64
  LOSS:
    NAME: modnet_loss
    AVERAGE: TRUE
  OPTIMIZER:
    name: adam
  TRAINER:
    TOTAL_STEP: 150000
  MACHINE:
    DEVICE: gpu
  VERBOSE: 1
  LOG_STEP: 10
  SAMPLE_STEP: 10
  MODEL_SAVE_STEP: 1
  VISUAL_DEBUG: False