# @package _global_
defaults:
  - config_schema
  - data@data.train: maadaamatting
  - dataloader@data.train.dataloader: maadaamattingloaderv2
  - transform@data.train.transforms: simple_transform
  - override hydra/sweeper: nevergrad
#  - override hydra/help: main_help



#CHECKPOINT:
#  DIR: "checkpoints"
#  CHECKPOINT_FREQUENCY: 1
data:
  train:
    name: "maadaa"
    image_path: "../data/dataset_split/train/"
    foreground_path: "../data/foregrounds_split/train/"
    background_path: "../data/backgrounds/"
    num_workers: 111
  val:
    name: "maadaa"
    image_path: "../data/dataset_split/train/"
mode: "train"
n_gpus: 8
#  TEST:
#    NAME: "maadaa"
#    IMAGE_PATH: "../data/one_image_dataset_split/val/"
##    Rewrite default dataloader
#    DATALOADER: ???
##    DATALOADER:
##      _target_: src.dataloader_hydra.MaadaaMattingLoaderV2
##      image_path: ${DATA.TEST.IMAGE_PATH}
##      foreground_path: ${DATA.TEST.FOREGROUND_PATH}
##      background_path: ${DATA.TEST.BACKGROUND_PATH}
##      image_size: ${DATA.TEST.IMAGE_SIZE}
##      batch_size: ${DATA.TEST.BATCH_SIZE}
##      mode: ${MODE}
#    BATCH_SIZE: 2
#    SHUFFLE: True
#    IMAGE_SIZE: 256
#    TRANSFORMS:
#      shared_pre:
#        - name: A.SmallestMaxSize
#          max_size: ${DATASET.TRAIN.IMAGE_SIZE}
#        - name: A.RandomCrop
#          height: ${DATASET.TRAIN.IMAGE_SIZE}
#          width: ${DATASET.TRAIN.IMAGE_SIZE}
#      composition:
#        - name: A.Normalize
#          mean: (0.5, 0.5, 0.5)
#          std: (0.5, 0.5, 0.5)
#      shared_post:
#        A.ToTensorV2
#    DROP_LAST: False
#MODEL:
#  NAME: modnet
#  BACKBONE:
#    NAME: resnet18
#    PRETRAINED: True
#  IN_CHANNELS: 3
#  HR_CHANNELS: 64
#LOSS:
#  NAME: modnet_loss
#  AVERAGE: TRUE
#OPTIMIZER:
#  name: adam
#TRAINER:
#  TOTAL_STEP: 150000
#MACHINE:
#  DEVICE: gpu
#WANDB:
#  PROJECT: alpha-matting
#  USER: bsuleymanov
#IS_TRAIN: True
#MODE: "train"
#VERBOSE: 1
#LOG_STEP: 10
#SAMPLE_STEP: 10
#MODEL_SAVE_STEP: 1
#MODEL_SAVE_PATH: "./models"
#INPUT_IMAGE_SAVE_PATH: "./input_save"
#VISUAL_DEBUG: False